name: "Infracost Compost"
description: Posts a comment to a github pull request or commit.
inputs:
  behavior:
    description: The behavior to use when posting comments.  Must be one of 'update' | 'delete_and_new' | 'hide_and_new' | 'new' | 'latest'.
    required: false
    default: update
  body:
    description: Specify the comment body content.
    required: false
  bodyFile:
    description: Specify a path to a file containing the comment body.  Mutually exclusive with body.
    required: false
  tag:
    description: Customize the comment tag. This is added to the comment as a markdown comment to detect the previously posted comments.
    required: false
  targetType:
    description: What object should be commented on.  Must be one of 'pr' or 'commit'.  When 'commit', the 'behavior' option will be ignored.
    required: false
    default: pr
  pullRequestNumber:
    description: 'The pull request number.  Defaults to the pull request number of the current event.'
    required: false
  repository:
    description: 'The GitHub owner and repository name. For example, infracost/compost-action. This defaults to {{ github.repository }}.'
    default: '${{ github.repository }}'
    required: false
  GITHUB_TOKEN:
    description: 'The GitHub access token (e.g. secrets.GITHUB_TOKEN) used to get the list of Infracost CLI versions. This defaults to {{ github.token }}.'
    default: '${{ github.token }}'
    required: false
outputs:
  latest:
    description: The body of the latest existing comment when using behavior 'latest'.
runs:
  using: node12
  main: dist/index.js
