name: "Infracost Compost"
description: Posts a comment to a github pull request or commit.
inputs:
  behavior:
    description: The behavior to use when posting comments. Must be one of 'update' | 'delete-and-new' | 'hide-and-new' | 'new' | 'latest'.
    required: false
    default: update
  body:
    description: Specify the comment body content.
    required: false
  body-file:
    description: Specify a path to a file containing the comment body. Mutually exclusive with body.
    required: false
  tag:
    description: Customize the comment tag. This is added to the comment as a markdown comment to detect the previously posted comments.
    required: false
  target-type:
    description: Which objects should be commented on. May be 'pull-request' or 'commit'.
    required: false
  github-token:
    description: Defaults to {{ github.token }}.
    default: '${{ github.token }}'
    required: false
outputs:
  body:
    description: The body of the comment. This is the latest existing comment when using behavior 'latest', and the comment that was posted otherwise.
runs:
  using: node12
  main: dist/index.js
