name: Test Setup

on:
  push:
    branches:
      - master
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test-comment:
    name: Test comment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Post comment
        uses: ./
        with:
          body: "This is a test comment."
      - name: Get comment
        uses: ./
        id: get_comment
        with:
          behavior: latest
      - name: Check comment
        run: |
          if [ "${{ steps.get_comment.outputs.latest }}" != "This is a test comment." ]; then
            echo "error::Expected comment 'This is a test comment.' got '${{ steps.get_comment.outputs.latest }}'"
            exit 1
          fi
  test-body-file:
    name: Test body file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Post comment
        uses: ./
        with:
          behavior: delete_and_new
          bodyFile: ./testdata/test-body-file.txt
          tag: test-body-file
      - name: Get comment
        uses: ./
        id: get_comment
        with:
          behavior: latest
          tag: test-body-file
      - name: Check comment
        shell: bash
        run: |
          expected=printf "$(cat ./testdata/test-body-file.txt)\n"
          if [ "${{ steps.get_comment.outputs.latest }}" != "$expected" ]; then
            echo "error::Expected comment '$expected' got '${{ steps.get_comment.outputs.latest }}'"
            exit 1
          fi
