name: Test Setup

on:
  push:
    branches:
      - master
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Post comment
        uses: ./
        with:
          body: "This is a test comment."
      - name: Get comment
        uses: ./
        id: get_comment
        with:
          behavior: latest
      - name: Check comment
        run: |
          if [ "${{ steps.get_comment.outputs.latest }}" != "This is a test comment." ]; then
            echo "error::Expected comment 'This is a test comment.' got '$${{ steps.get_comment.outputs.latest }}'"
            exit 1
          fi
